### ISSUE TITLE
Feedtype constants truncated

### ISSUE THREAD

**Issue by xeno** [vedmalex/mws-sdk#18]
Some of the feed type constants are truncated at present. They should all end with an underscore, making the truncated types easy to spot.

https://github.com/vedmalex/mws-sdk/blob/7d564825d268c574e93133a0634e8197d1f77f53/lib/feeds.js#L50

**Comment by vedmalex** [comment]
Hi @xeno done. it is in repo now!
Thank you for your contrubuition!
