### ISSUE TITLE
mws.js line 86 "request.qs = query;" does not pass query string to request.

### ISSUE THREAD

**Issue by davestacey** [vedmalex/mws-sdk#4]
When using "MWS.Feeds.requests.SubmitFeed()" (!api.upload) is false so the code is sending qs through "request.qs = query". The query parameters are not making it to Request. It works if you use requestOpts.qs = query.

Broken:
	if (!api.upload) {
		requestOpts.form = query;
	} else {
		request.qs = query;
	}
request(requestOpts, function(err, response, data) {...

Works:
	if (!api.upload) {
		requestOpts.form = query;
	} else {
		requestOpts.qs = query;
		// request.qs = query;
	}

**Comment by vedmalex** [comment]
the new version in npm
