### ISSUE TITLE
 query._FORMAT_ is undefined so there is no Content-Type.

### ISSUE THREAD

**Issue by davestacey** [vedmalex/mws-sdk#5]
When using "SubmitFeed()" to send xml in _Body_:
query._FORMAT_ is undefined so there is no Content-Type.

mws.js line 57 :

Broken:
requestOpts.headers = {
			'Content-Type': query._FORMAT_,
			'Content-MD5': crypto.createHash('md5').update(query._BODY_).digest('base64')
		};

Works:
requestOpts.headers = {
			'Content-Type': 'application/x-www-form-urlencoded',
			'Content-MD5': crypto.createHash('md5').update(query._BODY_).digest('base64')
		};

I don't see where we initially set query._FORMAT_.

**Comment by vedmalex** [comment]
Thank you.
merge is done.
see new version in npm
